services:
  - type: web
    name: discord-music-bot
    runtime: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    healthCheckPath: /
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: LAVALINK_HOST
        sync: false
      - key: LAVALINK_PASSWORD
        sync: false
      - key: LAVALINK_PORT
        value: "443"
      - key: LAVALINK_SECURE
        value: "true"
      - key: PORT
        value: "10000"
